### ISSUE TITLE
use sha256

### ISSUE THREAD

**Issue by ioistired** [ImpactDevelopment/maven#1]
https://shattered.io

**Comment by MattSturgeon** [comment]
Yep, sha1 is terrible for anything where security matters. What is it used for in maven?

Either way, if there's no reason not to use sha256 (or better) then we probably should.

**Comment by ZeroMemes** [comment]
To my understanding of Maven, the only kind of checksums that are put in place are MD5 and SHA-1 hashes. Refer to [this](http://maven.apache.org/plugins/maven-install-plugin/examples/installing-checksums.html).
 
> The Install Plugin can create integrity checksums (MD5, SHA-1) for the artifacts during installation.

If you are able to provide anything that would allow maven to process SHA-256 hashes, please do. Until then, I'm closing this issue.
